[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "luminescent"
version = "0.1.0"
authors = [
  { name="Paul Shen", email="pxshen@alumni.stanford.edu" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/paulxshen/Luminescent.jl"
Issues = "https://github.com/paulxshen/Luminescent.jl/issues"